# This smaller action (only r-release, only macOS) is scheduled to run daily
on:
  push:
  schedule:
  # Run at 2pm Sunday 
    - cron:  '5 4 * * 0'


name: Weekly-update-CRON

jobs:
  Update-Catalogue:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", "hutilscpp", "hutils", "readabs", "default"))
        shell: Rscript {0}
      - name: Update
        run: source("update.R")
        shell: Rscript {0}
      - name: Commit and push new files
        run: |
          git config --global user.name 'Hugh Parsonage'
          git config --global user.email 'hughparsonage@users.noreply.github.com'
          if [ -n "$(git status --porcelain)" ]; then git add -A && git commit -m 'Update data via GHA' && git push; fi
