# This smaller action (only r-release, only macOS) is scheduled to run daily
on:
  push:
  schedule:
  # Run at midnight everyday
    - cron:  '5 15 * * 0'


name: R-CMD-check-CRON

jobs:
  R-CMD-check:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", "hutilscpp", "hutils", "readabs"))
        shell: Rscript {0}
      - name: Update
        run: source("update.R")
        shell: Rscript {0}
      - name: Commit and push new files
        run: |
          git config --global user.name 'Hugh Parsonage'
          git config --global user.email 'hughparsonage@users.noreply.github.com'
          git add -A && git commmit -m 'Update data via GHA' && git push
